hmLoadTopic({
hmKeywords:"Inbound communication",
hmTitle:"Authorization",
hmDescription:"EDI Management Inbound communication is based on a REST JSON webservices and is using oAuth 2.0 authorization protocol.",
hmPrevLink:"version.html",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"D365FO Integration",
hmTitlePath:"D365FO Integration > Authorization",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Authorization<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">EDI Management Inbound communication is based on a REST JSON webservices and is using oAuth 2.0 authorization protocol.<\/p>\n\r<p class=\"p_Normal\">oAuth Authorization<\/p>\n\r<p class=\"p_Normal\">Some general info could be found here:<\/p>\n\r<p class=\"p_Normal\"><a href=\"https:\/\/docs.microsoft.com\/en-us\/azure\/active-directory\/develop\/v2-oauth2-auth-code-flow\" target=\"_blank\" class=\"weblink\">https:\/\/docs.microsoft.com\/en-us\/azure\/active-directory\/develop\/v2-oauth2-auth-code-flow<\/a>.<\/p>\n\r<p class=\"p_Normal\">For testing webservices, Postman application could be used with the following oAuth2.0 configuration to access D365 application.<\/p>\n\r<p class=\"p_Normal\"><img alt=\"clip0004\" style=\"margin:0;width:0.6250rem;height:0.6250rem;border:none\" src=\".\/images\/clip0004.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Callback URL - <a href=\"https:\/\/axudev952d8b716392020edevaos.cloudax.dynamics.com\/\" target=\"_blank\" class=\"weblink\">https:\/\/axudev952d8b716392020edevaos.cloudax.dynamics.com\/<\/a><\/p>\n\r<p class=\"p_Normal\">Auth URL - <a href=\"https:\/\/login.microsoftonline.com\/d3a267c2-2d78-478a-9435-d07aa77e59ad\/oauth2\/v2.0\/authorize\" target=\"_blank\" class=\"weblink\">https:\/\/login.microsoftonline.com\/d3a267c2-2d78-478a-9435-d07aa77e59ad\/oauth2\/v2.0\/authorize<\/a><\/p>\n\r<p class=\"p_Normal\">Access token URL - <a href=\"https:\/\/login.microsoftonline.com\/d3a267c2-2d78-478a-9435-d07aa77e59ad\/oauth2\/v2.0\/token\" target=\"_blank\" class=\"weblink\">https:\/\/login.microsoftonline.com\/d3a267c2-2d78-478a-9435-d07aa77e59ad\/oauth2\/v2.0\/token<\/a><\/p>\n\r<p class=\"p_Normal\">Client ID - f3a44ab8-aa33-43ff-bd86-ac8b2446b9f6<\/p>\n\r<p class=\"p_Normal\">Client Secret Key - Z9.5eBR5V2G36~RyY1u7Nhvb_94ozFxBd-<\/p>\n\r<p class=\"p_Normal\">Scope - <a href=\"https:\/\/axudev952d8b716392020edevaos.cloudax.dynamics.com\/.default\" target=\"_blank\" class=\"weblink\">https:\/\/axudev952d8b716392020edevaos.cloudax.dynamics.com\/.default<\/a><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
