hmLoadTopic({
hmKeywords:"",
hmTitle:"Configuration",
hmDescription:"EDI Management is installed with a set of default parameters. However, to use the module it is necessary to add configuration for each document, interface and integration...",
hmPrevLink:"navigation-and-menu-elements.html",
hmNextLink:"sales-processing.html",
hmParentLink:"index.html",
hmBreadCrumbs:"User manual",
hmTitlePath:"User manual > Configuration",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Configuration<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">EDI Management is installed with a set of default parameters. However, to use the module it is necessary to add configuration for each document, interface and integration party. A valid license key is needed to complete the configuration.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">EDI Management configuration should be performed in the following order:<\/p>\n\r<p class=\"p_Normal\">1. Refresh interfaces.<\/p>\n\r<p class=\"p_Normal\">2. Configure interfaces:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 0.8125rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>configure Lasernet reports for Outbound interfaces (if used)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 0.8125rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>configure Communication type (synchronous or asynchronous)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 0.8125rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>[for asynchronous interfaces] set up a batch job to process jobs from the interfaces<\/p>\n\r<p class=\"p_Normal\">3. Set up Validation rules<\/p>\n\r<p class=\"p_Normal\">4. Set up Validation profiles<\/p>\n\r<p class=\"p_Normal\">5. Set up Origins.<\/p>\n\r<p class=\"p_Normal\">6. Set up Parameters and add license key.<\/p>\n\r<p class=\"p_Normal\">7. Set up Rejection codes.<\/p>\n\r<p class=\"p_Normal\">8. Set up Endpoints.<\/p>\n\r<p class=\"p_Normal\">9. Set up Integration party.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
