hmLoadTopic({
hmKeywords:"",
hmTitle:"Endpoint",
hmDescription:"Endpoint configuration enables setup of communication parameters of systems that will receive messages sent from D365 F&O using  EDI Management.",
hmPrevLink:"interfaces2.html",
hmNextLink:"integration-party2.html",
hmParentLink:"index.html",
hmBreadCrumbs:"User manual &gt; Setup &gt; Interfaces",
hmTitlePath:"User manual > Setup > Interfaces > Endpoint",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Endpoint<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Endpoint configuration enables setup of communication parameters of systems that will receive messages sent from D365 F&amp;O using &nbsp;EDI Management.<\/p>\n\r<p class=\"p_Normal\">Endpoints are configured separately per each D365 F&amp;O company.<\/p>\n\r<p class=\"p_Normal\">Endpoints are used and set up on Outbound EDI Management interfaces and can be overwritten on the Integration Party setup in case specific endpoint is required for a business partner.<\/p>\n\r<p class=\"p_Normal\">EDI Management supports secure Rest WebServices as endpoint communication channel. The underlying HTTPS protocol can be additionally protected by using HTTP basic authentication.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Sample endpoint setup:<\/p>\n\r<p class=\"p_Normal\"><img alt=\"clip0080\" style=\"margin:0;width:2.0000rem;height:2.0000rem;border:none\" src=\".\/images\/clip0080.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Endpoint menu elements:<\/p>\n\r<p class=\"p_Normal\">1. Save - click \'Save\' to save the endpoint settings. <\/p>\n\r<p class=\"p_Normal\">2. New - click \'New\' to add a new endpoint.<\/p>\n\r<p class=\"p_Normal\">3. Delete - click \'Delete\' to remove an existing endpoint.<\/p>\n\r<p class=\"p_Normal\">4. List of endpoints - list of all configured endpoints.<\/p>\n\r<p class=\"p_Normal\">5. Endpoint - name of the selected endpoint.<\/p>\n\r<p class=\"p_Normal\">6. Connection type - type of the connection this endpoint supports. Currently EDI Management supports Web Service connections.<\/p>\n\r<p class=\"p_Normal\">7. Description - description of the API endpoint.<\/p>\n\r<p class=\"p_Normal\">8. Internet address - Remote HTTP(S) address that EDI Management will connect to when sending a message through this endpoint.<\/p>\n\r<p class=\"p_Normal\">9. User - user id for the HTTP basic authentication.<\/p>\n\r<p class=\"p_Normal\">10. Password - password for the HTTP basic authentication.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
