hmLoadTopic({
hmKeywords:"",
hmTitle:"Mappings",
hmDescription:"EDI Management mapping package is shipped in a zip file that can be deployed directly in BIS system.",
hmPrevLink:"mapdb.html",
hmNextLink:"http-listener.html",
hmParentLink:"seeburger-bis.html",
hmBreadCrumbs:"<a href=\"seeburger-bis.html\">Seeburger BIS<\/a> &gt; Deployment - in progress",
hmTitlePath:"Seeburger BIS > Deployment - in progress > Mappings",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Mappings<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">EDI Management mapping package is shipped in a zip file that can be deployed directly in BIS system.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Follow these steps to deploy the mappings:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">1. Open BIS and navigate to Configuration tab, Converter folder and select Mapping management option.<\/p>\n\r<p class=\"p_Normal\"><img alt=\"clip0036\" style=\"margin:0;width:2.0000rem;height:2.0000rem;border:none\" src=\".\/images\/clip0036.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">2. Click on Mapping file upload and navigate to the EDI Management maping package (filename pattern EDI Management_BIS_MAPPINGS_vX_Y.zip).<\/p>\n\r<p class=\"p_Normal\">Confirm selection by clicking Open.<\/p>\n\r<p class=\"p_Normal\"><img alt=\"clip0037\" style=\"margin:0;width:1.6250rem;height:1.6250rem;border:none\" src=\".\/images\/clip0037.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">3. The mapping package will be uploaded to the BIS system. Click Mapping File Deployment button to display the uploaded mappings.<\/p>\n\r<p class=\"p_Normal\">Confirm by clicking Deploy. <span style=\"font-weight: bold;\">Please note that the mapping list will differ depending on the EDI Management solution version<\/span>.<\/p>\n\r<p class=\"p_Normal\"><img alt=\"clip0038\" style=\"margin:0;width:1.7500rem;height:1.7500rem;border:none\" src=\".\/images\/clip0038.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">4. Progress bar will be shown for mappings deployment. The mappings will be deployed to &lt;Seeburger standard mappings&gt; project and will be highlighted after the deployment is completed. &nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
