pageinfo = [[1654852998,0,0,0,null],
	[1655715884,0,0,0,null],
	[1654852998,0,0,0,null],
	[1642428216,0,0,0,null],
	[1654852998,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655980962,0,0,0,null],
	[1655977020,0,0,0,null],
	[1655819988,0,0,0,null],
	[1655904910,0,0,0,null],
	[1648453744,0,0,0,null],
	[1655882658,0,0,0,null],
	[1642428398,0,0,0,null],
	[1642428276,0,0,0,null],
	[1642428508,0,0,0,null],
	[1668075884,0,0,0,null],
	[1654852998,0,0,0,null],
	[1649747694,0,0,0,null],
	[1649670272,0,0,0,null],
	[1654852998,0,0,0,null],
	[1654852998,0,0,0,null],
	[1657537122,0,0,0,null],
	[1655904928,0,0,0,null],
	[1657526834,0,0,0,null],
	[1620124450,0,0,0,null],
	[1655715922,0,0,0,null],
	[1667924826,0,0,0,null],
	[1655904892,0,0,0,null],
	[1657537604,0,0,0,null],
	[1655904920,0,0,0,null],
	[1655970494,0,0,0,null],
	[1648453744,0,0,0,null],
	[1660206816,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655882650,0,0,0,null],
	[1659692540,0,0,0,null],
	[1657207970,0,0,0,null],
	[1654852998,0,0,0,null],
	[1654852998,0,0,0,null],
	[1654853194,0,0,0,null],
	[1655715922,0,0,0,null],
	[1621496210,0,0,0,null],
	[1655715922,0,0,0,null],
	[1659696708,0,0,0,null],
	[1649676476,0,0,0,null],
	[1655987742,0,0,0,null],
	[1648453744,0,0,0,null],
	[1655882696,0,0,0,null],
	[1620124450,0,0,0,null],
	[1655715922,0,0,0,null],
	[1648453744,0,0,0,null],
	[1655904810,0,0,0,null],
	[1654852998,0,0,0,null],
	[1657533672,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655715922,0,0,0,null],
	[1642164462,0,0,0,null],
	[1621497892,0,0,0,null],
	[1655715922,0,0,0,null],
	[1621497914,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655715922,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655715922,0,0,0,null],
	[1660205378,0,0,0,null],
	[1655803848,0,0,0,null],
	[1648453744,0,0,0,null],
	[1655897034,0,0,0,null],
	[1654852998,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655715922,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655715922,0,0,0,null],
	[1621496286,0,0,0,null],
	[1621497864,0,0,0,null],
	[1621497876,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655803990,0,0,0,null],
	[1654852998,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655808506,0,0,0,null],
	[1662718750,0,0,0,null],
	[1668075276,0,0,0,null],
	[1667924944,0,0,0,null],
	[1621497972,0,0,0,null],
	[1621498016,0,0,0,null],
	[1655715922,0,0,0,null],
	[1621497994,0,0,0,null],
	[1621498030,0,0,0,null],
	[1655715922,0,0,0,null],
	[1621498042,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655715922,0,0,0,null],
	[1655715922,0,0,0,null],
	[1654852998,0,0,0,null],
	[1668076526,0,0,0,null],
	[1660206268,0,0,0,null],
	[1648453744,0,0,0,null],
	[1655904880,0,0,0,null],
	[1648453744,0,0,0,null],
	[1655904888,0,0,0,null],
	[1657529926,0,0,0,null],
	[1660206398,0,0,0,null],
	[1621499748,0,0,0,null]];
pagedata = [ ["./authorization.html","Authorization","EDI Management Inbound communication is based on a REST JSON webservices and is using oAuth 2.0 authorization protocol.","./images/zoomimage.jpg"],
["./authorization_2.html","Authorization","EDI Management Inbound communication is based on a REST JSON webservices and is using oAuth 2.0 authorization protocol.","./images/zoomimage.jpg"],
["./business-processes.html","Business processes","EDI Management solution introduces two new processes to the B2B.1 - Business Processes Seeburger Standard entities.","./images/zoomimage.jpg"],
["./class-diagrams.html","FXLIntegrationProcess","Created with Help+Manual 9 and styled with Premium Pack Version 5 &#169; by EC Software ","./images/zoomimage.jpg"],
["./classes.html","Classes","Name Developer description FXLBaseContract Base contract class for web services FXLCommunication Framework class for technical communication imple...","./images/zoomimage.jpg"],
["./classifier-mapping.html","Classifier mapping","In order to correctly detect, categorize and route messages from D365 a EDI Management classifier mapping is used. The name of the EDI Management ...","./images/zoomimage.jpg"],
["./collection-processing.html","Collection processing","This menu provides a summary of Collection interfaces processing. It groups and lists the import jobs by status. Each job can be accessed from the...","./images/zoomimage.jpg"],
["./collection-validation-journal.html","Collection validation journal","Collection validation journal is a dedicated job view that allows to review, edit and validate a document. A journal entry for a specific document...","./images/zoomimage.jpg"],
["./configuration.html","Configuration","EDI Management is installed with a set of default parameters. However, to use the module it is necessary to add configuration for each document, i...","./images/zoomimage.jpg"],
["./document-log.html","Document log","Document log provides an overview of two data sources: Integration jobs and Import journal. It is used to get a comprehensive insight into how inb...","./images/zoomimage.jpg"],
["./endpoint.html","Endpoint","Enter topic text here.","./images/zoomimage.jpg"],
["./endpoint2.html","Endpoint","Endpoint configuration enables setup of communication parameters of systems that will receive messages sent from D365 F&#38;O using  EDI Mana...","./images/zoomimage.jpg"],
["./fxlimportinterface.html","FXLImportInterface","Created with Help+Manual 9 and styled with Premium Pack Version 5 &#169; by EC Software ","./images/zoomimage.jpg"],
["./fxlintegrationevent.html","FXLIntegrationEvent","Created with Help+Manual 9 and styled with Premium Pack Version 5 &#169; by EC Software ","./images/zoomimage.jpg"],
["./fxlinterfacevalidation.html","FXLInterfaceValidation","Created with Help+Manual 9 and styled with Premium Pack Version 5 &#169; by EC Software ","./images/zoomimage.jpg"],
["./general-information.html","General information","Who should use this manual?  This manual is written for EDI Management and Enter value administrators and users. It provides instructions how...","./images/zoomimage.jpg"],
["./host-entities.html","Host entities","The setup assumes Seeburger Standard solution is used. ","./images/zoomimage.jpg"],
["./http-client-addresses.html","HTTP Client addresses","HTTP Client addresses configuration identifies each document endpoint that can be sent to D365 API. If there is a new endpoint developed on D365 s...","./images/zoomimage.jpg"],
["./http-client-connections.html","HTTP Client connections","In order to send messages to D365 it is necessary to set up HTTP connections and addresses. The HTTP Client connections define the host address of...","./images/zoomimage.jpg"],
["./http-listener.html","HTTP Listener and authentication","The fist step to establish connectivity between the D365 EDI Management and Seeburger BIS is to create an HTTP Listener in order to receive docume...","./images/zoomimage.jpg"],
["./http-server-partners.html","HTTP Server Partners","Following the HTTP Listener configuration it is necessary to set up HTTP Server Partners to specify the IP-range for inbound D365 EDI Management c...","./images/zoomimage.jpg"],
["./import-journal-posting.html","Import journal posting","This menu enables the setup and execution of a batch job that will try posting the EDI Management documents in approved status. The execution can ...","./images/zoomimage.jpg"],
["./import-journal.html","Import journal","Import journal in EDI Management provides basic information about the document received from one of the inbound interfaces and keeps track of the ...","./images/zoomimage.jpg"],
["./import-labels.html","Import labels","Import labels workspace allows for creation and printing of Label Cover pages which can be used during OCR scanning of invoices to facilitate impo...","./images/zoomimage.jpg"],
["./inbound.html","Inbound","Inbound documents are received via Web services based on a REST/JSON formats described bellow.","./images/zoomimage.jpg"],
["./inbound_2.html","Inbound","Inbound documents are received via Web services based on a REST/JSON formats described bellow.","./images/zoomimage.jpg"],
["./index.html","EDI Management","Enter topic text here.","./images/zoomimage.jpg"],
["./installation.html","Installation","The EDI Management for Dynamics 365 FO has to be imported into Microsoft Dynamics Lifecycle services(LCS) as a deployable package.","./images/zoomimage.jpg"],
["./integration-job-processing.html","Integration job processing","This menu enables the setup and execution of a batch job that will import integration jobs into  EDI Management Workspaces. The execution can...","./images/zoomimage.jpg"],
["./integration-jobs.html","Integration jobs","Integration jobs in EDI Management shows a technical report of all the messages that are sent out or received using interfaces. The list shows det...","./images/zoomimage.jpg"],
["./integration-monitor.html","Integration monitor","Integration monitor provides a workspace for monitoring the history of jobs processed by the interfaces and quick access to the configuration of E...","./images/zoomimage.jpg"],
["./integration-party.html","Integration party","Enter topic text here.","./images/zoomimage.jpg"],
["./integration-party2.html","Integration party","Integration party setup defines the inbound and outbound interfaces active for each customer and vendor account. The configuration also allows for...","./images/zoomimage.jpg"],
["./interfaces.html","Interfaces","This menu contains information about the installed EDI Management interfaces. They are grouped into inbound and outbound interfaces depending on w...","./images/zoomimage.jpg"],
["./interfaces2.html","Interfaces","In this menu you can configure inbound and outbound interfaces. Interfaces represent EDI Management capability to send or receive a specific docum...","./images/zoomimage.jpg"],
["./introduction.html","Introduction","EDI Management is a complete D365 Finance and Operations (F&#38;O) framework and module that enables F&#38;O the integration of external and inter...","./images/zoomimage.jpg"],
["./invoice-processing.html","Invoice processing","This workspace provides a summary of Purchase Invoice interfaces processing. It groups and lists the import jobs by status. Each job can be access...","./images/zoomimage.jpg"],
["./mapdb.html","MapDB","D365 EDI Management client uses BIS MapDB functionality to convert account numbers from different companies configured in D365.","./images/zoomimage.jpg"],
["./mappings.html","Mappings","EDI Management mapping package is shipped in a zip file that can be deployed directly in BIS system.","./images/zoomimage.jpg"],
["./message-header.html","Message header","Each XML document would contain FXLHeader section with some key message information:","./images/zoomimage.jpg"],
["./message-header_2.html","Message header","Each XML document would contain FXLHeader section with some key message information:","./images/zoomimage.jpg"],
["./message.html","Message contract","By default all incoming messages would contain \"message\" type element in the header defining some key parameters.","./images/zoomimage.jpg"],
["./message_2.html","Message contract","By default all incoming messages would contain \"message\" type element in the header defining some key parameters.","./images/zoomimage.jpg"],
["./navigation-and-menu-elements.html","Navigation and menu elements","EDI Management configuration can be accessed by clicking on EDI Management entry in the D365 F&#38;O navigation pane:","./images/zoomimage.jpg"],
["./oauth-endpoints.html","OAuth Endpoints","OAuth endpoint has to be configured before the HTTP Client configuration can be started. The OAuth endpoint will be used on HTTP Client address co...","./images/zoomimage.jpg"],
["./ocr-invoice-processing.html","OCR Invoice processing","This menu provides a summary of OCR Invoice processing interface. It groups and lists the imported documents by status. Each document can be acces...","./images/zoomimage.jpg"],
["./origin.html","Origin","Enter topic text here.","./images/zoomimage.jpg"],
["./origin2.html","Origin","Set up of sources of inbound documents and assignation of validation profiles.","./images/zoomimage.jpg"],
["./outbound.html","Outbound","Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.","./images/zoomimage.jpg"],
["./outbound_2.html","Outbound","Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.","./images/zoomimage.jpg"],
["./parameters.html","Parameters","Enter topic text here.","./images/zoomimage.jpg"],
["./parameters2.html","Parameters","EDI Management requires setup of the following parameters.","./images/zoomimage.jpg"],
["./partner-entities.html","Partner entities","Setup of partner entities is outside of the scope of EDI Management solution. The solution supports all types of Customer and Trading Partner setu...","./images/zoomimage.jpg"],
["./pending-vendor-invoices.html","Pending vendor invoices","This workspace is an extension of a default Enter value workspace for Pending vendor invoices which displays only documents imported from OCR Invo...","./images/zoomimage.jpg"],
["./purchase-confirmation.html","Purchase confirmation","Purchase confirmation send function, executed from Purchase confirmation journal form in D365FO.","./images/zoomimage.jpg"],
["./purchase-confirmation_2.html","Purchase confirmation","Purchase confirmation send function, executed from Purchase confirmation journal form in D365FO.","./images/zoomimage.jpg"],
["./purchase-order-create.html","Purchase order create","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/createPurchTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-create_2.html","Purchase order create_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/createSalesTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-create_2_2.html","Purchase order create_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/createSalesTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-create_3.html","Purchase order create_3","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLCustCollectionService/confirmCollecti...","./images/zoomimage.jpg"],
["./purchase-order-create_3_2.html","Purchase order create_3","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLCustCollectionService/confirmCollecti...","./images/zoomimage.jpg"],
["./purchase-order-create_4.html","Purchase order create","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/createPurchTable &#38;n...","./images/zoomimage.jpg"],
["./purchase-order-send.html","Purchase order","Purchase order send function, executed from Purchase orders form in D365FO.","./images/zoomimage.jpg"],
["./purchase-order-send_2.html","Purchase order","Purchase order send function, executed from Purchase orders form in D365FO.","./images/zoomimage.jpg"],
["./purchase-order-validation-jour.html","Purchase order validation journal","Purchase order validation journal is a dedicated job view that allows to review, edit and validate a document. A journal entry for a specific docu...","./images/zoomimage.jpg"],
["./purchase-processing.html","Purchase processing","This menu provides a summary of Purchase interfaces processing. It groups and lists the import jobs by status. Each job can be accessed from the l...","./images/zoomimage.jpg"],
["./rejection-code.html","Rejection code","Enter topic text here.","./images/zoomimage.jpg"],
["./rejection-code2.html","Rejection code","Rejection codes are used to define the items in the list used when rejecting a document in the Import journal workspace. ","./images/zoomimage.jpg"],
["./rules.html","Rules","An additional rule need to be set up to enable processing incoming D365 EDI Management client with Seeburger standard solution. ","./images/zoomimage.jpg"],
["./sales-invoice.html","Sales invoice","Sales invoice send function, executed from Sales invoice journal form in AX.","./images/zoomimage.jpg"],
["./sales-invoice_2.html","Sales invoice","Sales invoice send function, executed from Sales invoice journal form in AX.","./images/zoomimage.jpg"],
["./sales-order-confirmation.html","Sales order confirmation","Sales order confirmation send function, executed from Sales order confirmations form in AX.","./images/zoomimage.jpg"],
["./sales-order-confirmation_2.html","Sales order confirmation","Sales order confirmation send function, executed from Sales order confirmations form in AX.","./images/zoomimage.jpg"],
["./sales-order-update.html","Sales order update","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/updateSalesTable &#38;n...","./images/zoomimage.jpg"],
["./sales-order-update_2.html","Sales order update_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/confirmPurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_2_2.html","Sales order update_2_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/invoicePurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_2_2_2.html","Sales order update_2_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/invoicePurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_2_3.html","Sales order update_2","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLPurchTableService/confirmPurchTable &#38;...","./images/zoomimage.jpg"],
["./sales-order-update_3.html","Sales order update","Webservice URL: https://axudev952d8b716392020edevaos.cloudax.dynamics.com/api/services/FXLInboundServices/FXLSalesTableService/updateSalesTable &#38;n...","./images/zoomimage.jpg"],
["./sales-order-validation-journal.html","Sales order validation journal","Sales order validation journal is a dedicated job view that allows to review, edit and validate a document. A journal entry for a specific documen...","./images/zoomimage.jpg"],
["./sales-packing-slip.html","Sales packing slip","Sales packing slip send function, executed from Sales packing slip journal form in AX.","./images/zoomimage.jpg"],
["./sales-packing-slip_2.html","Sales packing slip","Sales packing slip send function, executed from Sales packing slip journal form in AX.","./images/zoomimage.jpg"],
["./sales-processing.html","Sales processing","This menu provides a summary of Sales interfaces processing. It groups and lists the import jobs by status. Each job can be accessed from the list...","./images/zoomimage.jpg"],
["./security-configuration.html","Security configuration","EDI Management is shipped with a predefined set of privileges. The following chapter describes what each privilege refers to and what level of acc...","./images/zoomimage.jpg"],
["./security-configuration_2.html","Security configuration_2","EDI Management is shipped with a predefined set of privileges. The following chapter describes what each privilege refers to and what level of acc...","./images/zoomimage.jpg"],
["./seeburger-bis.html","Seeburger BIS","Enter topic text here.","./images/zoomimage.jpg"],
["./seexmlmapping.html","SEEXMLMapping","Mapping name: FXL_PurchaseOrder_TO_SEEDELFOR_V3_0  FXL_PurchaseOrder (Source message) Condition SEEDELFOR_V3_0 (Destination message) Report.P...","./images/zoomimage.jpg"],
["./seexmlmapping_2.html","SEEXMLMapping_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_2_2.html","SEEXMLMapping_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3.html","SEEXMLMapping_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_2.html","SEEXMLMapping_3_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_2_2.html","SEEXMLMapping_3_2","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_3.html","SEEXMLMapping_3_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_3_2.html","SEEXMLMapping_3_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_3_4.html","SEEXMLMapping_3","in progress","./images/zoomimage.jpg"],
["./seexmlmapping_4.html","SEEXMLMapping","Mapping name: FXL_PurchaseOrder_TO_SEEDELFOR_V3_0  FXL_PurchaseOrder (Source message) Condition SEEDELFOR_V3_0 (Destination message) Report.P...","./images/zoomimage.jpg"],
["./tables.html","Tables","Name Developer description FXLCustCollectionLine The FXLCustCollectionLine table contains imported line data for collection interface. FXLCustColl...","./images/zoomimage.jpg"],
["./terms-of-use.html","Terms of use","No part of this publication may be reproduced, transmitted, transcribed, or translated into any language in any form by any means without the prio...","./images/zoomimage.jpg"],
["./validaiton-journal.html","Validation journal","The validation journal for invoice processing is a dedicated job view that allows to review, edit and validate a document and uses Purchase order ...","./images/zoomimage.jpg"],
["./validation-profile.html","Validation profile","Enter topic text here.","./images/zoomimage.jpg"],
["./validation-profile2.html","Validation profile","In order to attach rules to import process it is necessary to create and setup a validation profile. A validation profile contains all the rules r...","./images/zoomimage.jpg"],
["./validation-rules.html","Validation rules","Enter topic text here.","./images/zoomimage.jpg"],
["./validation-rules2.html","Validation rules","Validation rules contain a catalog of separate pre-programmed checks performed at various stages on the inbound documents integrated using EDI Man...","./images/zoomimage.jpg"],
["./vendor-imported-invoices.html","Vendor imported invoices","Vendor imported invoices is part of the OCR Invoice processing module. This workspace provides an overview of all invoices imported through OCR in...","./images/zoomimage.jpg"],
["./vendor-invoice-validation-jour.html","Vendor invoice validation journal","Vendor invoice validation journal is a dedicated job view that allows to review, edit and validate an invoice. A journal entry for a specific docu...","./images/zoomimage.jpg"],
["./version.html","Version","FXL-01-001 - 20.03.2021 FXL-01-002 - 28.03.2021 FXL-01-003 - 07.04.2021 FXL-01-004 - 21.04.2021 FXL-01-005 - 03.05.2021 FXL-01-006 - 20.05.2021","./images/zoomimage.jpg"]];
