hmLoadTopic({
hmKeywords:"",
hmTitle:"Origin",
hmDescription:"Set up of sources of inbound documents and assignation of validation profiles.",
hmPrevLink:"integration-party2.html",
hmNextLink:"rejection-code2.html",
hmParentLink:"index.html",
hmBreadCrumbs:"User manual &gt; Setup",
hmTitlePath:"User manual > Setup > Origin",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Origin<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Set up of sources of inbound documents and assignation of validation profiles.<\/p>\n\r<p class=\"p_Normal\">Each source of an inbound document handled by EDI Management has to be defined in the Origin setup. Additionally, a validation profile can be assigned to an Origin entry. It will be applied to an inbound document unless another profile is selected on Integration party setup.<\/p>\n\r<p class=\"p_Normal\">Sample setup:<\/p>\n\r<p class=\"p_Normal\"><img alt=\"clip0072\" style=\"margin:0;width:2.0000rem;height:2.0000rem;border:none\" src=\".\/images\/clip0072.png\"\/><\/p>\n\r<p class=\"p_Normal\">The following parameters need to be set up for a new entry:<\/p>\n\r<div style=\"text-align: left; text-indent: 0; padding: 0 0 0 0; margin: 0 0 0 0;\"><table style=\"border:solid 0.1250rem #808080; border-spacing:0; border-collapse:collapse;\">\n\r<thead>\n\r<tr>\n\r<th style=\"vertical-align:top; background-color:#808080; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\"><span style=\"font-weight: bold; color: #ffffff;\">Parameter name<\/span><\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; background-color:#808080; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\"><span style=\"font-weight: bold; color: #ffffff;\">Default value<\/span><\/p>\n\r<\/th>\n\r<th style=\"vertical-align:top; background-color:#808080; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\"><span style=\"font-weight: bold; color: #ffffff;\">Description<\/span><\/p>\n\r<\/th>\n\r<\/tr>\n\r<\/thead>\n\r<tbody>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">Origin<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">none<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">Origin Id<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">Name<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">none<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">Name of the origin system. The value needs to match the REST API endpoint header value \'fromSystem\'.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">Validation profile Id<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">none<\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:solid thin #808080;\"><p class=\"p_Normal\">Drop-down list.<\/p>\n\r<p class=\"p_Normal\">Selection of configured validation profiles.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/tbody>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
