hmLoadTopic({
hmKeywords:"",
hmTitle:"Outbound",
hmDescription:"Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.",
hmPrevLink:"purchase-order-create_3_2.html",
hmNextLink:"message-header_2.html",
hmParentLink:"index.html",
hmBreadCrumbs:"User manual &gt; Rest API &gt; Documents",
hmTitlePath:"User manual > Rest API > Documents > Outbound 2",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Outbound<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.<\/p>\n\r"
})
