hmLoadTopic({
hmKeywords:"",
hmTitle:"Outbound",
hmDescription:"Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.",
hmPrevLink:"purchase-order-create_3.html",
hmNextLink:"message-header.html",
hmParentLink:"index.html",
hmBreadCrumbs:"<a href=\"index.html\">EDI Management<\/a> &gt; Documents",
hmTitlePath:"EDI Management > Documents > Outbound",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-after: avoid;\"><span class=\"f_Heading1\">Outbound<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">Outbound documents are sent via Seeburger Web service. XML file generated by LaserNet report connector is attached to the call.<\/p>\n\r"
})
